### ISSUE TITLE
Outdated Markdown plugin instructions

### ISSUE THREAD

**Issue by hoffm386** [learn-co-curriculum/dsc-git-resources#1]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x] Instructions
- [ ] Other (explain below)

### Source

```
#### Markdown plugins and apps
  - [Sublime MD Preview Plugin](https://github.com/revolunet/sublimetext-markdown-preview)
  - [Mou MD writer app](http://mouapp.com/)
  - [Atom text editor](https://atom.io) has a markdown preview built in.
```

### Concern

The linked Sublime plugin is archived and should be removed.

## (Optional) Proposed Solution

In the DS program we typically recommend VS Code as the text editor, so there should be tips for that if we want to have Markdown tips here. Alternatively we could just remove the Markdown content from this lesson because we cover it elsewhere

**Comment by christine-egan42** [comment]
removed outdated markdown plugins
